markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/

google_analytics_id: UA-50755011-1
google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

repository: https://github.com/wpsinc/api-documentation-jekyll
branch: gh-pages

timezone: America/Boise

collections:
  docs:
    output: true

name: WPS API • Version 4.0
description: Our API provides a way for our dealers to communicate with our system by transmitting data over the internet.
url: http://docs.wps-inc.com

twitter:
  username: wps_dist

logo: /img/wps-logo-498x230_1478618045.png

gems:
  - jekyll-feed
  - jekyll-redirect-from
#  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
#  - jekyll-avatar
#  - jekyll-mentions

exclude:
  - .git/
  - .idea/
  - .sass-cache/
  - _site/
  - .gitignore
  - CNAME
  - README.md
